name: Streamkeys
markdown: redcarpet
highlighter: pygments
url: http://localhost:4000
exclude: ['*.scss']
baseTitle: Streamkeys - Global Music Player Hotkeys for Chrome -
destination: ./build/_site
gems: [jekyll-assets]
source: ./code
assets:
  sources:
    - _assets/javascripts
    - _assets/images
    - _assets/stylesheets
navigation:
  faq: faq.html
  help: guide.html
  sitelist: sites.html
  home: index.html
  contact: contact.html
  changelog: changelog.html
sitelist:
  - name: 8tracks
    image: icons/8tracks.png
    url: www.8tracks.com
  - name: Bandcamp
    image: icons/bandcamp.png
    url: www.bandcamp.com
  - name: Deezer
    image: icons/deezer.png
    url: www.deezer.com
  - name: Di.fm
    image: icons/difm.png
    url: www.di.fm
  - name: Earbits
    image: icons/earbits.png
    url: www.earbits.com
  - name: Google Play
    image: icons/googleplay.png
    url:: play.google.com
  - name: Grooveshark
    image: icons/grooveshark.png
    url: www.grooveshark.com
  - name: TheHypeMachine
    image: icons/hypemachine.png
    url: www.hypem.com
  - name: iHeartRadio
    image: icons/iheart.png
    url: www.iheart.com
  - name: Jango
    image: icons/jango.png
    url: www.jango.com
  - name: MixCloud
    image: icons/mixcloud.png
    url: www.mixcloud.com
  - name: Pandora
    image: icons/pandora.png
    url: www.pandora.com
  - name: RadioParadise
    image: icons/radioparadise.png
    url: www.radioparadise.com
  - name: Rdio
    image: icons/rdio.png
    url: www.rdio.com
  - name: Spotify
    image: icons/spotify.png
    url: www.spotify.com
  - name: Songstr
    image: icons/songstr.png
    url: www.songstr.com
  - name: Songza
    image: icons/songza.png
    url: www.songza.com
  - name: Stitcher
    image: icons/stitcher.png
    url: www.stitcher.com
  - name: Soundcloud
    image: icons/soundcloud.png
    url: www.soundcloud.com
  - name: Slacker
    image: icons/slacker.png
    url: www.slacker.com
  - name: YouTube
    image: icons/youtube.png
    url: www.youtube.com
  - name: VK
    image: icons/vk.png
    url: www.vk.com
  - name: Plex
    image: icons/plex.png
    url: www.plex.tv
  - name: TheSixtyOne
    image: icons/thesixtyone.png
    url: www.thesixtyone.com
  - name: 7digital
    image: icons/7digital.png
    url: www.7digital.com
  - name: Amazon Music
    image: icons/amazon.png
    url: www.amazon.com
  - name: NPR Infinite Player
    image: icons/npr.png
    url: one.npr.org
changelog:
  - version: v1.4.0
    content: >
      -Added support for Yandex Music, PocketCasts (thanks <a href="https://github.com/Rorgy" target="_blank">@Rorgy</a>!), Ambient Sleeping Pill (thanks <a href="https://github.com/inverse" target="_blank">@inverse</a>!)<br>
      -Fix bugs with Jango, VK, Deezer and iHeartRadio
  - version: v1.3.6
    content: >
      -Added support for Bop.fm, Last.fm, Sony Music Unlimited (thanks <a href="https://github.com/inverse" target="_blank">@inverse</a>!), Pleer (thanks <a href="https://github.com/ulex" target="_blank">@ulex</a>!), YouAreListening.to
  - version: v1.3.5
    content: >
      -Fixed bugs with Jango<br>
      -Added support for YouTube (disabled by default, enable on options page!), Plex.tv, Amazon Cloud Player, NPR Infinite Player, 7digital
  - version: v1.3.4
    content: >
      -Fixed bugs with Songza and Slacker Radio<br>
      -Added support for di.fm, player.edge.ca, RadioParadise, Songstr
  - version: v1.3.3
    content: >
      -Fixed bug introduced in 1.3.2 that broke functionality. Big thanks to those users who submitted bug reports!
  - version: v1.3.2
    content: >
      -Added an options page which lets you enable/disable sites. To get to the options page go to the extension tab in Chrome (thanks <a href="https://github.com/dreyks" target="_blank">@Dreyks</a>!)<br>
      -Added support for Seesu.me, iHeartRadio, Mixcloud<br>
      -Fixed bug where having different players open at same time causes issues
  - version: v1.3.1
    content: >
      -Added support for VK, Stitcher<br>
      -Fixed Google Music clicking inputs twice
  - version: v1.3.0
    content: >
      -Added support for global hotkeys across entire system. <a href="guide.html#global">Read here for more info</a><br>
      -Added support for: Earbits, Songza<br>
      -Fixed Google Music support (thanks <a href="https://github.com/findmory-livefyre" target="_blank">@findmory</a>!)
  - version: v1.2.0
    content: >
      -Reworked the whole extension so that capturing works much better and from anywhere on the chrome window<br>
      -Added support for Google Music, Jango, Thesixtyone, Slacker<br>
      -Removed the options page
  - version: v1.1.0
    content: >
      -Added support for 8tracks, Deezer, Pandora, Spotify, Soundcloud, Hypemachine and Myspace<br>
      -Media keys now default to enabled
  - version: v1.0.5
    content: >
      -Added support for Rdio<br>
      -Fixed some problems with option page
  - version: v1.0
    content: >
      -Chrome Webstore release
  - version: v0.9.5
    content: >
      -Added hotkey support for Bandcamp
  - version: v0.9
    content: >
      -Media key support added<br>
      -Added an option page which can be accessed via the chrome extension tab
  - version: v0.8
    content: >
      -Initial release
