name: Streamkeys
markdown: redcarpet
highlighter: pygments
url: http://localhost:4000
exclude: ['sinatra', 'Guardfile', 'Gemfile', 'Gemfile.lock', 'node_modules', 'bower_components',
  'streamkeys-site.sublime-project', 'credentials.json', 'Gruntfile.js', 'package.json', 'README.md']
baseTitle: Streamkeys - Global Music Player Hotkeys for Chrome -
navigation:
  faq: faq.html
  help: guide.html
  sitelist: sites.html
  home: index.html
  contact: contact.html
  changelog: changelog.html
sitelist:
  - name: 8tracks
    image: icons/8tracks.png
    url: www.8tracks.com
  - name: Bandcamp
    image: icons/bandcamp.png
    url: www.bandcamp.com
  - name: Deezer
    image: icons/deezer.png
    url: www.deezer.com
  - name: Di.fm
    image: icons/difm.png
    url: www.di.fm
  - name: Earbits
    image: icons/earbits.png
    url: www.earbits.com
  - name: Google Play
    image: icons/googleplay.png
    url:: play.google.com
  - name: Grooveshark
    image: icons/grooveshark.png
    url: www.grooveshark.com
  - name: TheHypeMachine
    image: icons/hypemachine.png
    url: www.hypem.com
  - name: iHeartRadio
    image: icons/iheart.png
    url: www.iheart.com
  - name: Jango
    image: icons/jango.png
    url: www.jango.com
  - name: MixCloud
    image: icons/mixcloud.png
    url: www.mixcloud.com
  - name: Pandora
    image: icons/pandora.png
    url: www.pandora.com
  - name: RadioParadise
    image: icons/radioparadise.png
    url: www.radioparadise.com
  - name: Rdio
    image: icons/rdio.png
    url: www.rdio.com
  - name: Spotify
    image: icons/spotify.png
    url: www.spotify.com
  - name: Songstr
    image: icons/songstr.png
    url: www.songstr.com
  - name: Songza
    image: icons/songza.png
    url: www.songza.com
  - name: Stitcher
    image: icons/stitcher.png
    url: www.stitcher.com
  - name: Soundcloud
    image: icons/soundcloud.png
    url: www.soundcloud.com
  - name: Slacker
    image: icons/slacker.png
    url: www.slacker.com
  - name: YouTube
    image: icons/youtube.png
    url: www.youtube.com
  - name: VK
    image: icons/vk.png
    url: www.vk.com
  - name: Plex
    image: icons/plex.png
    url: www.plex.tv
  - name: TheSixtyOne
    image: icons/thesixtyone.png
    url: www.thesixtyone.com
